name: Deploy Suhail XMD Bot

on:
  push:
    branches:
      crazypixel959

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Change to the version of Node.js you're using

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Modify if you are using a different testing framework

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure build job completes first

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute deployment
        env:
          NODE_ENV: production
          DEPLOYMENT_SECRET: ${{ secrets.DEPLOYMENT_SECRET }}  # Use your deployment secrets
        run: |
          npm run build &&  # Build your project if necessary
          npm run deploy  # Adjust this command to match your deployment process
